hackclub/YSWS-Catalog

README.md
index.html
programs.json
script.js
styles.css

This pull request improves the YSWS Catalog with updates to functionality and user experience across key files:
- **README.md**: Added features like search, theme toggle, and deadline indicators. Instructions and program attributes were expanded.
- **index.html**: Introduced sorting options, "Ending Soon" filter, and a detailed program modal.
- **script.js**: Enhanced the `formatDeadline` function for better date handling.
- **programs.json**: Updated program details, corrected Slack URLs, and added new entries.

Enhancements to YSWS Catalog

---

data.yml
index.html
script.js
styles.css

- **Category Update:** Renamed the "Upcoming" category to "Draft" and adjusted corresponding styles for consistency.
- **Event Status Management:** Implemented automatic status updates for programs, marking them as "completed" based on their deadlines.
- **Participant Information:** Added participant counts to program details and enhanced the display with updated styling.
- **Code Refactoring:** Streamlined the participant count display by introducing a dedicated formatting function and reorganized program loading to separate active and completed events for better maintainability.

Rename 'Upcoming' to 'Draft', Add Participant Counts, and Refactor Status Handling

---

data.yml
index.html

Added an entry to the website called 'Printboard YSWS' to the website! It was just copied from the #ysws-finder list. I'm new to coding and websites, so any comments/suggestions are welcome!

Added Printboard!

---

README.md

Updated contribution example in the readme.md to YML and referenced data.yml

Update readme example form JSON to YML

---

data.yml

Add saycheese to the list!

---

data.yml

add minus twelve

---

script.js

Ensured everything was loaded before beginning renderprograms using promise.all and a async function

Ensured everything was loaded before beginging renderprograms

---

data.yml

moved Minus Twelve to the `limitedTime` category and added a `deadline` key.
if this looks correct, **please merge ASAP**: i will be announcing this YSWS in just 11 minutes.

activate minus twelve

---

data.yml

Updating the name of the channel for the printboard ysws to fit what it is in the slack

Update channel name of printboard ysws

---

data.yml

added printboard

---

data.yml

Add Juice and Jungle to the list of yswses in data.yml

Add Juice and Jungle

---

data.yml

Add the new upcoming ysws hackducky !

Update data.yml and add Hackducky YSWS !

---

data.yml

changed high seas, neon and say cheese to be completed.

Update ysws list to be more up to date.

---

data.yml

It's not a ysws or official hack club program and I never put it on here, so idk how it got here

Removing draw sticker get sticker from the list

---

data.yml

Move limited time YSWSes above indefinite, at the request of msw

Move limited time YSWSes above indefinite

---

data.yml

please merge at 10:00AM EST or later!

add black box

---

data.yml

Include a new draft entry for the Hack the Line YSWS.

Add Hack the Line to drafts

---

data.yml

Fix invalid end date for Browser Buddy

Fix invalid end date for Browser Buddy

---

data.yml

This isn't an official program, nor is it currently running

Remove community newsletter

---

script.js

See #48. 
This PR just adds a check to make sure programsList exists and is an array.

Fix empty programslist causing failure to load

---

data.yml

All other active ysws are organized on date of completion

Organization of PixelDust

---

data.yml

The person who runs this would not like it to be on the ysws site

Removed Draw Sticker Get Sticker

---

data.yml

migrate to pixeldust.hackclub.com

---

styles.css

Increase Readability of hero-cards

---

data.yml

https://visioneer.hackclub.com

Added #visioneer to data.yml

---

data.yml

Add the new hacklet ysws to the site

Add hacklet to active yswses

---

data.yml

Added Hack A Home(Draft) & Edited Status For Ended YSWS's

Added Hack A Home & Edited Status

---

data.yml

Reformats Hack Drive to use properly formatted name + add website link

Reformat Hack Drive + Add website link

---

data.yml

Moved solder from drafts to currently active.

Add solder

---

data.yml

These were previously drafts, I was going to move RPG too, but V1 has finished

Moved Sidequests and Lockin to Limited Time 

---

data.yml

fraps end date has been announced as june 30th

Fraps end date

---

data.yml

terminal craft is back for v2!

---

data.yml

Add Converge

---

data.yml

Clarify that you can submit any type of program and you will receive a dongle and antenna kit

Update Waveband description

---

data.yml

Add cmd + k

---

data.yml

adding the dummies YSWS to the data.yaml

Add Dummies YSWS

---

data.yml

updated portal-vr deadline

---

README.md
api.json
data.yml
feed.xml

I did this as a start to a bug pull request, this will have a lot of changes later on due to me making YSWS Pirate where they can request to have their YSWS added and I add it here.

Fixxed readme and added Slack channel url to grub

---

data.yml

```yaml
- name: issued
description: code to design hack-themed apparel
detailedDescription: you code to design hack-themed apparel, we ship popular designs as real clothes!
website: https://issued-ysws.vercel.app
slack: https://hackclub.slack.com/archives/C09C9M0N2UC
slackChannel: "#issued"
status: draft
```

feat(data): issued

---

data.yml

Add foodie YSWS to the catalog!

Add foodie YSWS

---

index.html

Move GitHub link to Hack Club repo
